name: Block-Elevators
version: 1.0.0
main: jp.havenmc.blockelevators.BlockElevators
api-version: '26.1'
author: ryusei_sky
folia-supported: true

commands:
  block-elevators-reload:
    permission: blockelevators.reload

permissions:
  blockelevators.use:
    default: true
  blockelevators.reload:
    default: op
